### ISSUE TITLE
Feedback1

### ISSUE THREAD

**Issue by LotteHind** [aumath-advancedr2019/Permutation1#19]
### 1. Purpose of the package

The description of the package in the vignette and the documentation is very clear, easy to read and not too long (which is nice). 

### 2. Completeness

The functions are nice and fulfill the purpose well. Especially nice that you have included the permutation_lm function as well. Thereby making it more diverse and useful when the data is not divided into groups.  

Your examples include the generation of a dataset to use in the functions. It works and is easy to figure out.  
But another way of showing how to use the functions, could be by including an example dataset, maybe with real-world values to answer a real-world problem. And not just random simulated numbers.

The description file of the package needs updated information, like the Authors and that ggplot and magrittr is required and imported when loading package.  

### 3. Code quality and sophistication

No installation problems and nice that you specify how to install and what to do if a problem occurs, in your vignette - very professional! 

The functions are robust when trying on another dataset (Plantgrowth)

It is nice that the functions outputs an object of class "htest", which results in a nice printed output. It is nice that both the inputs and the outputs from the functions are more or less the same - very intuitive. 
Maybe the plot() function could be incorporated to take the output instead of the function always returning a plot. 

Nice touch with the progress bar.

### 4. Documentation

Very nice that all descriptions are easy to read and match each other

Description for permutation_median and permutation_mean: "count"? Cant figure out what it is based on your examples but does not understand the description of this option. Also the group1 and group2 description has the same line (small thing, but could be: "name of group1" and "name of group2").

In the examples you write: nice_plot = plot_status. Maybe write False or True in the examples instead. I had to go into the documentation to figure out what nice_plot is and change its value, to be able to run the examples. 

Another thing is that it might be more intuitive if nice_plot = F did not create a plot at all. Instead when nice_plot = T, make ggplot if it is present and base R plot if not. 

Again, your vignette is very nice with good examples of printed output and plots. 

### 5. Interface

Very nice interface and you are consistent in your argument naming which makes it easy to switch between your functions. 

It is nice that your function prints a warning if it is more suitable to make a parametric t-test. 

### 7. Conclusion

I like that your package both provide a way of doing permutation when the data consists of groups and when it is from a linear model. Furthermore I like your vignette with a good description of permutation and how you calculate your p-value. I like your output, both that the "htest" object that is printed nicely and your plots. 

Possible improvements: 

 - Include a dataset with more real-world data that can be used as an example of a real-worl problem where your package might be useful. 
 - Since permutation_mean and permutation_median are very alike maybe an argument to the function could specify if the mean or median should be used, instead of having two functions. 
 - The Package Description file should be updated
 - Maybe an option to not plot anything. 
 - Maybe call plot() on the "htest" output, giving your nice plots.

**Comment by SolveigOe** [comment]
Thankt you for the nice feedback :)
