### ISSUE TITLE
Feedback - Christian

### ISSUE THREAD

**Issue by chrskalborg** [aumath-advancedr2019/Permutation1#21]
### 1. Purpose of the package

Carried by a very good describtive vignette, tha purpose of the package is indeed very clear.

### 2. Completeness

I think, that since you are including way to generate some data, for demonstating of the package functions, it would be nice, if you included data with the package, so that the user did not need to generate some themself.

### 3. Code quality and sophistication

The package installed without any issues.

I see, that you have used S3 object programming, by the class 'htest'. However, I think, that istead of writing function plot_permtaion(), as a function it self, you could just define the plotting function htest.plot() altering the defualt plot function, such that the permutation plot function would be used, when calling plot() on an object of class 'htest'. As far as I see, you are not using the full potetial of 'htest' class.

Finally the functions worked well on my own examples.

### 4. Documentation

As stated above, vignette is very good. I like, that the help pages are consistent with each other, so the user becomes familar with the layout fast, and they are easy to read and understand. Lastly they all include good examples.

### 5. Interface

You use consistent input naming, which I find very nice, since it makes using the functions all together very nice.

The documentation UI are similar to the packages we know already, which is nice.

Lastly, is find it nice, that you are providing stop() and warning() issues, the secure that the user are using the functions correctly.

### 6. Additional comments
I do not have any additional comments

### 7. Conclusion
All in all a good package. Spend a little time, to fully endorse S3 objects, by rewriting, such that the plot_permutaion, is now just to call plot() on an object of class 'htest'.

**Comment by ute** [comment]
Good an thorough report (@chrskalborg) :-) 
I disagree though with writing a function `plot.htest`, because `htest` is a class used by many tests. However, one can define an additional class with plot method, fx. `permutationtest`. Then the result would have `class(result) <- c("permutationtest", "htest")`, and one can make a function `plot.permutationtest`.

**Comment by chrskalborg** [comment]
Oh, my bad, I did not realise 'htest' was a predefined class. But that was exactly what I meant, regarding making the class 'permutationtest' then :)

**Comment by SolveigOe** [comment]
Thank you for the nice feedback :)
We have chosen not to change anything, since we like it how it is, but it is nice to know how to :)
